version: "3.5"
services:
  jellyfin:
    image: jellymatt
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jellymatt-test
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/opt/jellyfin/config
      - /shares/tv:/shares/tv
      - /shares/movies:/shares/movies
    ports:
      - 8096:8096
#      - 8920:8920 #optional
#      - 7359:7359/udp #optional
#      - 1900:1900/udp #optional
    restart: always
    network_mode: bridge
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
