version: "3.5"
services:
  jellyfin:
    image: jellyfin-matt
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jellyfin-matt
    environment:
      - TZ=America/Los_Angeles
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./config/data:/var/lib/jellyfin
      - ./config/config:/etc/jellyfin
      - ./config/log:/var/log/jellyfin
      - /shares/tv:/shares/tv
      - /shares/movies:/shares/movies
    ports:
      - 8096:8096
#      - 8920:8920 #optional
#      - 7359:7359/udp #optional
#      - 1900:1900/udp #optional
    restart: always
    network_mode: bridge
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
